name: Cron Job Demo
on:
  push:
  schedule:
    - cron: '50 06 * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "💡 The ${{ github.owner }} repository has been cloned to the runner."
      - run: echo "💡 The ${{ secrets.TOKEN }} ."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: run npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run start
        env:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
