name: Cron Job Demo
on:
  push:
  schedule:
    - cron: '50 06 * * *'
jobs:
  Explore-GitHub-Actions:      
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: run npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: run start
        env: 
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
        run: npm run start            
      - run: echo "🍏 This job's status is ${{ job.status }}."
